FROM node:slim

WORKDIR /work

COPY app app
COPY assets assets
COPY .watchmanconfig .watchmanconfig
COPY *.js ./
COPY *.json ./

RUN npm install expo-cli
RUN npm install

ENTRYPOINT ["npm", "run", "android"]
