version: '3'
services:
  android-emulator:
    image: butomo1989/docker-android-x86-${butomoVersion}
    container_name: android-emulator
    ports:
      - 6080:6080
      - 5554:5554
      - 5555:5555
    environment:
      - DEVICE=Samsung Galaxy S6
    privileged: true
  expo:
    build:
      context: .
      dockerfile: Dockerfile-expo
    expose:
      - 8080
      - 4443
### share volume
volumes:
    app-volume:

# docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container butomo1989/docker-android-x86-8.1
# docker run -it --rm -v $PWD/android-testing/ui/espresso/BasicSample:/root/tmp butomo1989/docker-android-x86-8.1 tmp/gradlew build
