from node:latest
label version=0.0.1

run npm install -g expo-cli

run apt-get update && \
	yes | apt-get install zip && \
	wget -q https://dl.google.com/android/repository/platform-tools-latest-linux.zip && \
	unzip -q platform-tools-latest-linux.zip && \
	rm platform-tools-latest-linux.zip && \
	export PATH=$PATH:/platform-tools

copy code/ /app
workdir /app

entrypoint [ "expo", "android" ]
# cmd adb connect emulator
