from node:latest
label version=0.0.1

env PATH="/platform-tools:${PATH}"

copy ecosystem/run-expo-app.sh /app/

run npm install -g expo-cli
run apt-get update && \
  yes | apt-get install zip apt-utils && \
	wget -q https://dl.google.com/android/repository/platform-tools-latest-linux.zip && \
	unzip -q platform-tools-latest-linux.zip && \
	rm platform-tools-latest-linux.zip && \
  chmod +x app/run-expo-app.sh

env DOCKERIZE_VERSION v0.6.1
run wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

workdir /app

healthcheck CMD curl -f http://emulator:6080/ || exit 1

cmd ./run-expo-app.sh
