from node:latest
label version=0.0.1

workdir /home/node

user node
copy ecosystem/run-expo-app.sh .
env PATH=/home/node/platform-tools:${PATH}

user root
run apt-get update && \
  yes | apt-get install zip apt-utils && \
  chmod +x run-expo-app.sh && \
  chown node run-expo-app.sh
run npm install -g expo-cli

user node
env DOCKERIZE_VERSION v0.6.1
run wget -q https://dl.google.com/android/repository/platform-tools-latest-linux.zip && \
	unzip -q platform-tools-latest-linux.zip && \
	rm platform-tools-latest-linux.zip
run wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
  tar -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
  rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

cmd ./run-expo-app.sh
