version: '3'
services:
  emulator:
    # Solution taken from https://github.com/butomo1989/docker-android
    image: butomo1989/docker-android-x86-8.1
    container_name: emulator
    ports:
      - 6080:6080
    environment:
      - DEVICE=Samsung Galaxy S6
    privileged: true

  expo:
    build:
      context: ../
      dockerfile: ecosystem/Dockerfile-expo
    container_name: expo
    volumes:
      - "../code:/code"
    depends_on:
      - emulator
