version: '3'
services:
  emulator:
    # Solution taken from https://github.com/butomo1989/docker-android
    image: budtmo/docker-android-x86-10.0
    container_name: emulator
    ports:
      - 6080:6080
      - 5554:5554
      - 5555:5555
    environment:
      - DEVICE=Nexus 5
    privileged: true

  expo:
    build:
      context: ../
      dockerfile: ecosystem/Dockerfile-expo
    container_name: expo
    volumes:
      - ../code:/home/node/code
    depends_on:
      - emulator
